apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   version: v1

# namePrefix: v1-convenience-



resources:
- ../base

# transformers:
# - ./transformers/name-prefix.yml
# - ./transformers/label.yml



# transformers:
# - |-
#   apiVersion: builtin
#   kind: PrefixSuffixTransformer
#   metadata:
#     name: my-prefix-transformer
#   prefix: v1-inline-
#   ## suffix: -transformers-inline
#   fieldSpecs:
#   - path: metadata/name


# nameSuffix: -transformers