apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: techtalk-labels

# labels:
# - pairs:
#     version: techtalk-labels
#   includeSelectors: true
#   includeTemplates: false

commonAnnotations:
  annotated-by: kustomize

namePrefix: techtalk-labels-

resources:
- mysql
- ../base