apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: techtalk-secret

namePrefix: techtalk-secret-
nameSuffix: -v1

resources:
- mysql
- ../base
- namespace.yml

namespace: techtalk-ns