apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   version: techtalk-labels

labels:
- pairs:
    version: techtalk-labels
  includeSelectors: false
  includeTemplates: true

commonAnnotations:
  annotated-by: kustomize

namePrefix: techtalk-

resources:
- mysql
- ../base