apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: techtalk-ns

namePrefix: techtalk-ns-

namespace: techtalk-ns

# transformers:
#   - ./transformers/namespace.yml

resources:
- mysql
- ../base
- namespace.yml 